GtkWidget* layout1;
GtkWidget* PaternEntry;
GtkWidget* AvailSpacesBox;
GtkWidget* label1;
GtkWidget* PermutateCheck;
GtkWidget* ResultBox;
GtkWidget* ActionButton;
GtkWidget **Collection;
GtkWidget* Mainwindow;
static gint delete_event_cb(GtkWidget* w, GdkEventAny* e, gpointer data);